Repository TheCodeMonks/NYTimes-App, pull requests merged in 2020-10, with the labels that each got.

#13 Support Light Mode & Dark Mode
  .idea/.name
  .idea/codeStyles/Project.xml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  LICENSE
  app/build.gradle
  app/src/main/java/www/thecodemonks/techbytes/NYTimes.kt
  app/src/main/java/www/thecodemonks/techbytes/datastore/UIModePreference.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/articles/ArticlesFragment.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/base/BaseActivity.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/bookmarks/BookmarksFragment.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/viewmodel/ArticleViewModel.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/viewmodel/ViewModelProviderFactory.kt
  app/src/main/java/www/thecodemonks/techbytes/utils/TimeUtils.kt
  app/src/main/res/drawable/ic_outline_dark.xml
  app/src/main/res/layout/fragment_articles.xml
  app/src/main/res/layout/fragment_bookmarks.xml
  app/src/main/res/menu/menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/fragment_articles_scene.xml
  app/src/main/res/xml/fragment_bookmarks_scene.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: Hacktoberfest

#20 Add Swipe refresh
  app/src/main/java/www/thecodemonks/techbytes/repo/Repo.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/articles/ArticlesFragment.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/viewmodel/ArticleViewModel.kt
  app/src/main/res/layout/fragment_articles.xml
Labels: hacktoberfest-accepted

#37 Implement View binding on recycler view adapter
  app/src/main/java/www/thecodemonks/techbytes/ui/adapter/CategoryAdapter.kt
  app/src/main/java/www/thecodemonks/techbytes/ui/adapter/NewsAdapter.kt
Labels: enhancement, hacktoberfest-accepted
